"""One-episode sweep of matched initial leg pose and wheel-ground spawn height."""

import argparse
import csv
from pathlib import Path
from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser()
parser.add_argument("--task", default="TanchoV3-Flat-v0")
parser.add_argument("--max_steps", type=int, default=300)
parser.add_argument("--scan_gains", action="store_true")
parser.add_argument(
    "--balanced_candidates",
    default=None,
    help="CSV generated by optimize_initial_pose.py; tests its exact COM-balanced poses.",
)
parser.add_argument("--output", default="logs/diagnostics/initial_pose_scan.csv")
AppLauncher.add_app_launcher_args(parser)
args = parser.parse_args()
app = AppLauncher(args).app

import gymnasium as gym
import torch
from isaaclab_tasks.utils import parse_env_cfg
import tancho_v3_lab.tasks  # noqa: F401
from tancho_v3_lab.tasks.direct.tancho_v3 import custom_events as ce


def main():
    thighs = [-0.9, -0.7, -0.5, -0.3, -0.1]
    calves = [0.8, 1.1, 1.4, 1.7, 2.0, 2.3]
    gain_pairs = [(stiffness, damping) for stiffness in (5, 15, 25, 50, 100) for damping in (1, 2, 4)]
    if args.balanced_candidates:
        with Path(args.balanced_candidates).open(newline="", encoding="utf-8") as handle:
            poses = [
                (float(row["thigh_rad"]), float(row["calf_rad"]))
                for row in csv.DictReader(handle)
            ]
        gains_by_env = []
    elif args.scan_gains:
        # Gain conclusions must survive more than one kinematic configuration.
        # Cross the requested gains with three symmetric, FK-supported poses.
        scan_cases = [
            (pose, gain)
            for pose in ((-0.1, 0.1), (-0.5, 0.87), (0.4, 0.4))
            for gain in gain_pairs
        ]
        poses = [pose for pose, _ in scan_cases]
        gains_by_env = [gain for _, gain in scan_cases]
    else:
        poses = [(thigh, calf) for thigh in thighs for calf in calves]
        gains_by_env = []
    cfg = parse_env_cfg(args.task, device=args.device, num_envs=len(poses))
    cfg.seed = 42
    env = gym.make(args.task, cfg=cfg)
    env.reset()
    core = env.unwrapped
    robot = core.scene["robot"]
    device = core.device
    if args.scan_gains:
        stiffness = robot.data.joint_stiffness.clone()
        damping = robot.data.joint_damping.clone()
        for index, (kp, kd) in enumerate(gains_by_env):
            for name in ("joint_thigh_L", "joint_thigh_R", "joint_calf_L", "joint_calf_R"):
                joint_id = robot.joint_names.index(name)
                stiffness[index, joint_id] = kp
                damping[index, joint_id] = kd
        robot.write_joint_stiffness_to_sim(stiffness)
        robot.write_joint_damping_to_sim(damping)
    leg = torch.tensor(poses, device=device)
    # Use the same URDF-FK/collision-support source as production reset.  Each
    # candidate pose therefore receives its own root Z; there is no guessed
    # wheel radius or hand-maintained analytic link-length expression here.
    root_z = torch.tensor(
        [
            ce.compute_reset_root_height(
                {
                    "joint_thigh_L": thigh,
                    "joint_thigh_R": thigh,
                    "joint_calf_L": calf,
                    "joint_calf_R": calf,
                    "joint_wheel_L": 0.0,
                    "joint_wheel_R": 0.0,
                }
            )
            for thigh, calf in poses
        ],
        device=device,
        dtype=robot.data.root_pos_w.dtype,
    )
    root_pose = robot.data.root_pose_w.clone()
    root_pose[:, 2] = root_z
    joint_pos = robot.data.joint_pos.clone()
    for name, column in (("joint_thigh_L", 0), ("joint_thigh_R", 0), ("joint_calf_L", 1), ("joint_calf_R", 1)):
        joint_pos[:, robot.joint_names.index(name)] = leg[:, column]
    robot.write_root_pose_to_sim(root_pose)
    robot.write_root_velocity_to_sim(torch.zeros_like(robot.data.root_vel_w))
    robot.write_joint_state_to_sim(joint_pos, torch.zeros_like(joint_pos))
    core.sim.forward()
    core.scene.update(0.0)
    wheel_z = robot.data.body_pos_w[:, [robot.body_names.index("wheel_L"), robot.body_names.index("wheel_R")], 2]
    support = torch.tensor(
        [ce.compute_wheel_support_geometry({
            "joint_thigh_L": thigh, "joint_thigh_R": thigh,
            "joint_calf_L": calf, "joint_calf_R": calf,
            "joint_wheel_L": 0.0, "joint_wheel_R": 0.0,
        }).wheel_support_distance_m for thigh, calf in poses],
        device=device,
        dtype=wheel_z.dtype,
    )
    print("INITIAL_POSE_WHEEL_GAP", (wheel_z - support).tolist(), flush=True)
    action_term = core.action_manager.get_term("joint_pos")
    actions = torch.zeros(env.action_space.shape, device=device)
    for action_index, joint_id in enumerate(action_term._joint_ids):
        name = robot.joint_names[joint_id]
        value = leg[:, 0] if "thigh" in name else leg[:, 1]
        default = cfg.scene.robot.init_state.joint_pos[name]
        actions[:, action_index] = (value - default) / cfg.actions.joint_pos.scale
    first_done = torch.zeros(len(poses), dtype=torch.bool, device=device)
    steps = torch.zeros(len(poses), dtype=torch.long, device=device)
    minimum_z = root_z.clone()
    reason = ["running"] * len(poses)
    contact = core.scene.sensors["contact_forces"]
    contact_names = contact.body_names
    first_contact = ["none"] * len(poses)
    leg_ids = [
        robot.joint_names.index(name)
        for name in ("joint_thigh_L", "joint_calf_L", "joint_thigh_R", "joint_calf_R")
    ]
    effort_limits = robot.data.joint_effort_limits[:, leg_ids]
    max_leg_torque = torch.zeros(len(poses), device=device)
    saturated_samples = torch.zeros(len(poses), dtype=torch.long, device=device)
    active_samples = torch.zeros(len(poses), dtype=torch.long, device=device)
    max_root_z_error = torch.zeros(len(poses), device=device)
    nonwheel_contact_samples = torch.zeros(len(poses), dtype=torch.long, device=device)
    wheel_contact_indices = {
        index for index, name in enumerate(contact_names) if name in ("wheel_L", "wheel_R")
    }
    for step in range(args.max_steps):
        active = ~first_done
        minimum_z[active] = torch.minimum(minimum_z[active], robot.data.root_pos_w[active, 2])
        forces = torch.linalg.vector_norm(contact.data.net_forces_w, dim=-1)
        for index in torch.where(active)[0].tolist():
            if first_contact[index] == "none":
                touching = [contact_names[j] for j, force in enumerate(forces[index].tolist()) if force >= 10.0]
                if touching:
                    first_contact[index] = ",".join(touching)
        with torch.inference_mode():
            _, _, terminated, truncated, _ = env.step(actions)
        torque = robot.data.applied_torque[:, leg_ids].abs()
        max_leg_torque[active] = torch.maximum(max_leg_torque[active], torque[active].amax(dim=1))
        saturated = (torque >= 0.98 * effort_limits).any(dim=1)
        saturated_samples[active] += saturated[active].long()
        active_samples[active] += 1
        max_root_z_error[active] = torch.maximum(
            max_root_z_error[active], (robot.data.root_pos_w[active, 2] - root_z[active]).abs()
        )
        forces_after = torch.linalg.vector_norm(contact.data.net_forces_w, dim=-1)
        if wheel_contact_indices:
            nonwheel_ids = [index for index in range(len(contact_names)) if index not in wheel_contact_indices]
            if nonwheel_ids:
                has_nonwheel_contact = (forces_after[:, nonwheel_ids] >= 10.0).any(dim=1)
                nonwheel_contact_samples[active] += has_nonwheel_contact[active].long()
        steps[active] += 1
        newly_done = active & (terminated | truncated)
        for index in torch.where(newly_done)[0].tolist():
            reason[index] = ",".join(
                name for name in core.termination_manager.active_terms
                if bool(core.termination_manager.get_term(name)[index])
            )
        first_done |= newly_done
        if bool(first_done.all()):
            break
    rows = []
    for index, (thigh, calf) in enumerate(poses):
        label = (
            f"thigh={thigh:.2f} calf={calf:.2f} stiffness={gains_by_env[index][0]} damping={gains_by_env[index][1]}"
            if args.scan_gains
            else f"thigh={thigh:.2f} calf={calf:.2f}"
        )
        saturation_fraction = float(saturated_samples[index]) / max(int(active_samples[index]), 1)
        nonwheel_fraction = float(nonwheel_contact_samples[index]) / max(int(active_samples[index]), 1)
        row = {
            "thigh_rad": thigh,
            "calf_rad": calf,
            "stiffness": gains_by_env[index][0] if args.scan_gains else "",
            "damping": gains_by_env[index][1] if args.scan_gains else "",
            "computed_root_height_m": float(root_z[index]),
            "survival_steps": int(steps[index]),
            "minimum_root_z_m": float(minimum_z[index]),
            "max_root_z_error_m": float(max_root_z_error[index]),
            "max_leg_torque_Nm": float(max_leg_torque[index]),
            "leg_torque_saturation_fraction": saturation_fraction,
            "nonwheel_contact_fraction": nonwheel_fraction,
            "termination_reason": reason[index],
            "first_contact": first_contact[index],
        }
        rows.append(row)
        print(
            f"INITIAL_POSE {label} root_z={float(root_z[index]):.4f} "
            f"first_steps={int(steps[index])} minimum_z={float(minimum_z[index]):.4f} "
            f"max_z_error={float(max_root_z_error[index]):.4f} "
            f"max_leg_tau={float(max_leg_torque[index]):.3f} sat={saturation_fraction:.3f} "
            f"nonwheel={nonwheel_fraction:.3f} reason={reason[index]} "
            f"first_contact={first_contact[index]}", flush=True,
        )
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"INITIAL_POSE_CSV {output.resolve()}", flush=True)
    env.close()


if __name__ == "__main__":
    main()
    app.close()
