"""Tancho V3 wheel-only balance task (``TanchoV3-WheelOnly-Flat-v0``).

Self-contained manager-based task.  Nothing here imports ``tasks/direct``; the
few pieces worth keeping (flat plane material, IMU mounting, DM-H3510 wheel
actuator) are copied and documented in ``README.md``.

Physical model
--------------
* Asset ``Tancho_v3_wheel_only.urdf`` is generated by
  ``scripts/wheel_only/build_wheel_only_urdf.py`` from the working-tree
  ``Tancho_v3.urdf``: base + both legs at thigh=-0.50 rad / calf=+0.87 rad are
  merged into ONE rigid body with the exact combined mass, COM and inertia.
  The legs therefore have no DOF at all (stricter than a fixed joint or a stiff
  PD lock); ``scripts/wheel_only/verify_leg_pose.py`` recovers the frozen
  angles from the asset.
* Only ``joint_wheel_L`` / ``joint_wheel_R`` move.  Wheel actuator = DM-H3510
  velocity mode, 0.45 N*m peak, 188 rad/s sim velocity limit (unchanged).

Timing: 200 Hz PhysX, 50 Hz policy (decimation 4).  See README for why.
"""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path

import isaaclab.envs.mdp as mdp
import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg, AssetBaseCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import ImuCfg
from isaaclab.terrains import TerrainImporterCfg
from isaaclab.utils import configclass
from isaaclab.utils.noise import UniformNoiseCfg as Unoise

URDF_PATH = Path(__file__).resolve().parents[2] / "assets" / "robots" / "Tancho_v3" / "urdf" / "Tancho_v3_wheel_only.urdf"

# -- timing -------------------------------------------------------------------
SIM_DT_S = 0.005  # 200 Hz PhysX
DECIMATION = 4  # 50 Hz policy / action update (0.02 s)

# -- failure set (same threshold as the LQR push experiment) ---------------------
FAILURE_TILT_RAD = math.radians(15.0)

# -- DM-H3510 wheel motor (copied unchanged from the existing Tancho tasks) --------
WHEEL_JOINTS = ["joint_wheel_L", "joint_wheel_R"]
WHEEL_EFFORT_LIMIT_NM = 0.45
WHEEL_VELOCITY_LIMIT_RAD_S = 188.0
WHEEL_VELOCITY_DAMPING = 4.0  # velocity-loop Kd, Kp = 0
WHEEL_RATED_SPEED_RAD_S = 52.3598776  # 500 rpm; action = +/-1 -> +/-rated speed

# -- IMU mounting on base_link_root (copied from tancho_v3_env_cfg) ----------------
IMU_POS_ROOT = (-0.00835741999, 0.0000000160456, -0.0294337942)
IMU_ROT_ROOT = (0.707106781, 0.707106781, 0.0, 0.0)

# Nominal ground friction; robot material 0.8 x plane 0.8 (multiply) as in Flat.
NOMINAL_FRICTION = 0.8


def _root_height_on_flat_ground(urdf_path: Path) -> float:
    """Root Z that puts both round-tire cylinders tangent to z=0 at zero pitch."""
    root = ET.parse(urdf_path).getroot()
    heights = []
    for side in ("L", "R"):
        axle_z = float(root.find(f"joint[@name='joint_wheel_{side}']/origin").get("xyz").split()[2])
        radius = float(root.find(f"link[@name='wheel_{side}']/collision/geometry/cylinder").get("radius"))
        heights.append(radius - axle_z)
    if abs(heights[0] - heights[1]) > 1.0e-9:
        raise RuntimeError(f"Asymmetric wheel support heights: {heights}")
    return heights[0]


ROOT_HEIGHT_M = _root_height_on_flat_ground(URDF_PATH)
# Spawn 1 mm above contact so a +/-0.05 rad reset pitch (<=0.6 mm drop at the
# tire) never starts in penetration.
RESET_CLEARANCE_M = 0.001


@configclass
class WheelOnlySceneCfg(InteractiveSceneCfg):
    terrain = TerrainImporterCfg(
        prim_path="/World/ground",
        terrain_type="plane",
        collision_group=-1,
        physics_material=sim_utils.RigidBodyMaterialCfg(
            friction_combine_mode="multiply",
            restitution_combine_mode="multiply",
            static_friction=NOMINAL_FRICTION,
            dynamic_friction=NOMINAL_FRICTION,
            restitution=0.0,
        ),
        debug_vis=False,
    )
    light = AssetBaseCfg(
        prim_path="/World/light",
        spawn=sim_utils.DomeLightCfg(intensity=2000.0, color=(0.85, 0.85, 0.85)),
    )
    robot: ArticulationCfg = ArticulationCfg(
        prim_path="/World/envs/env_.*/Robot",
        spawn=sim_utils.UrdfFileCfg(
            asset_path=str(URDF_PATH),
            fix_base=False,
            merge_fixed_joints=True,
            self_collision=False,
            joint_drive=None,
            activate_contact_sensors=False,
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.0, 0.0, ROOT_HEIGHT_M + RESET_CLEARANCE_M),
            rot=(1.0, 0.0, 0.0, 0.0),
            joint_pos={name: 0.0 for name in WHEEL_JOINTS},
            joint_vel={name: 0.0 for name in WHEEL_JOINTS},
        ),
        actuators={
            "wheels": ImplicitActuatorCfg(
                joint_names_expr=WHEEL_JOINTS,
                stiffness=0.0,
                damping=WHEEL_VELOCITY_DAMPING,
                effort_limit_sim=WHEEL_EFFORT_LIMIT_NM,
                velocity_limit_sim=WHEEL_VELOCITY_LIMIT_RAD_S,
            )
        },
    )
    imu = ImuCfg(
        prim_path="/World/envs/env_.*/Robot/base_link_root",
        offset=ImuCfg.OffsetCfg(pos=IMU_POS_ROOT, rot=IMU_ROT_ROOT),
        debug_vis=False,
    )


@configclass
class ActionsCfg:
    """Two wheel velocity targets (DM-H3510 velocity mode), nothing else."""

    wheel_vel = mdp.JointVelocityActionCfg(
        asset_name="robot",
        joint_names=WHEEL_JOINTS,
        scale=WHEEL_RATED_SPEED_RAD_S,
        use_default_offset=True,
        preserve_order=True,
    )


@configclass
class CommandsCfg:
    """Zero velocity command; only consumed by the built-in tracking rewards."""

    base_velocity = mdp.UniformVelocityCommandCfg(
        asset_name="robot",
        resampling_time_range=(10.0, 10.0),
        rel_standing_envs=1.0,
        rel_heading_envs=0.0,
        heading_command=False,
        ranges=mdp.UniformVelocityCommandCfg.Ranges(
            lin_vel_x=(0.0, 0.0), lin_vel_y=(0.0, 0.0), ang_vel_z=(0.0, 0.0), heading=(0.0, 0.0)
        ),
    )


_WHEELS = SceneEntityCfg("robot", joint_names=WHEEL_JOINTS, preserve_order=True)


@configclass
class ObservationsCfg:
    @configclass
    class PolicyCfg(ObsGroup):
        """Hardware-measurable only: IMU attitude + gyro, wheel encoder speed, last action (10 dims)."""

        imu_projected_gravity = ObsTerm(
            func=mdp.imu_projected_gravity, params={"asset_cfg": SceneEntityCfg("imu")}, noise=Unoise(n_min=-0.02, n_max=0.02)
        )
        imu_ang_vel = ObsTerm(
            func=mdp.imu_ang_vel, params={"asset_cfg": SceneEntityCfg("imu")}, noise=Unoise(n_min=-0.05, n_max=0.05), scale=0.25
        )
        wheel_vel = ObsTerm(func=mdp.joint_vel_rel, params={"asset_cfg": _WHEELS}, noise=Unoise(n_min=-0.2, n_max=0.2), scale=0.05)
        last_action = ObsTerm(func=mdp.last_action)

        def __post_init__(self):
            self.enable_corruption = True
            self.concatenate_terms = True

    @configclass
    class CriticCfg(ObsGroup):
        """Privileged, noise-free state for the value function only (never deployed)."""

        base_lin_vel = ObsTerm(func=mdp.base_lin_vel, scale=2.0)
        base_ang_vel = ObsTerm(func=mdp.base_ang_vel, scale=0.25)
        projected_gravity = ObsTerm(func=mdp.projected_gravity)
        wheel_vel = ObsTerm(func=mdp.joint_vel_rel, params={"asset_cfg": _WHEELS}, scale=0.05)
        last_action = ObsTerm(func=mdp.last_action)

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = True

    policy: PolicyCfg = PolicyCfg()
    critic: CriticCfg = CriticCfg()


@configclass
class RewardsCfg:
    """Built-in Isaac Lab terms only.  Weights are per second (the manager multiplies by step_dt=0.02)."""

    # Survival: +20 for a full 20 s episode; a fall costs an extra 200*0.02 = 4.
    is_alive = RewTerm(func=mdp.is_alive, weight=1.0)
    termination_penalty = RewTerm(func=mdp.is_terminated, weight=-200.0)
    # Upright: |g_xy|^2 = sin^2(tilt); 5 deg costs 0.076/s.
    upright = RewTerm(func=mdp.flat_orientation_l2, weight=-10.0)
    # Pitch/roll rate damping.
    ang_vel_xy = RewTerm(func=mdp.ang_vel_xy_l2, weight=-0.05)
    # Stand still: zero commanded planar speed and yaw rate.  std=0.25 m/s makes
    # 0.1 m/s cost 15% of the term.
    lin_vel_xy = RewTerm(func=mdp.track_lin_vel_xy_exp, weight=1.0, params={"command_name": "base_velocity", "std": 0.25})
    ang_vel_z = RewTerm(func=mdp.track_ang_vel_z_exp, weight=0.5, params={"command_name": "base_velocity", "std": 0.25})
    # L1 keeps a constant pull toward exactly zero wheel speed, which the exp
    # term above does not (its gradient vanishes at 0).  Removes slow drift.
    wheel_vel_l1 = RewTerm(func=mdp.joint_vel_l1, weight=-0.02, params={"asset_cfg": _WHEELS})
    # Effort, normalized by the peak: both wheels saturated costs 0.02/s.
    wheel_torque = RewTerm(func=mdp.joint_torques_l2, weight=-0.01 / WHEEL_EFFORT_LIMIT_NM**2, params={"asset_cfg": _WHEELS})
    action_rate = RewTerm(func=mdp.action_rate_l2, weight=-0.01)
    wheel_vel_limit = RewTerm(func=mdp.joint_vel_limits, weight=-1.0, params={"soft_ratio": 0.9, "asset_cfg": _WHEELS})


@configclass
class TerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)
    # Tilt of the body z-axis from vertical.  With two coaxial wheels roll is
    # ~0, so this is |pitch| > 15 deg.  No contact termination: in +/-15 deg only
    # the tires reach the ground (first non-wheel contact is the thigh box at
    # -59.6 deg; see README).
    tilt = DoneTerm(func=mdp.bad_orientation, params={"limit_angle": FAILURE_TILT_RAD})


@configclass
class EventsCfg:
    """Training randomization.  Every term here is disabled in the Play/eval config."""

    physics_material = EventTerm(
        func=mdp.randomize_rigid_body_material,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot"),
            "static_friction_range": (0.6, 1.0),
            "dynamic_friction_range": (0.6, 1.0),
            "restitution_range": (0.0, 0.0),
            "num_buckets": 64,
            "make_consistent": True,
        },
    )
    add_base_mass = EventTerm(
        func=mdp.randomize_rigid_body_mass,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=["base_link_root"]),
            "mass_distribution_params": (-0.15, 0.25),  # about -6%/+10% of 2.55 kg
            "operation": "add",
        },
    )
    reset_base = EventTerm(
        func=mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {"pitch": (-0.05, 0.05)},
            "velocity_range": {"x": (-0.1, 0.1), "pitch": (-0.2, 0.2)},
        },
    )
    reset_wheels = EventTerm(
        func=mdp.reset_joints_by_offset,
        mode="reset",
        params={"asset_cfg": _WHEELS, "position_range": (0.0, 0.0), "velocity_range": (0.0, 0.0)},
    )
    # Adds a sampled horizontal velocity to the chassis.  0.8 m/s on the 2.62 kg
    # robot is 2.1 N*s, i.e. the 42 N x 50 ms pulse of the push sweep.
    push_robot = EventTerm(
        func=mdp.push_by_setting_velocity,
        mode="interval",
        interval_range_s=(3.0, 6.0),
        params={"velocity_range": {"x": (-0.8, 0.8)}},
    )


@configclass
class TanchoV3WheelOnlyFlatEnvCfg(ManagerBasedRLEnvCfg):
    scene: WheelOnlySceneCfg = WheelOnlySceneCfg(num_envs=4096, env_spacing=2.0)
    actions: ActionsCfg = ActionsCfg()
    commands: CommandsCfg = CommandsCfg()
    observations: ObservationsCfg = ObservationsCfg()
    rewards: RewardsCfg = RewardsCfg()
    terminations: TerminationsCfg = TerminationsCfg()
    events: EventsCfg = EventsCfg()
    curriculum = None

    def __post_init__(self):
        self.sim.dt = SIM_DT_S
        self.decimation = DECIMATION
        self.sim.render_interval = DECIMATION
        self.episode_length_s = 20.0


@configclass
class TanchoV3WheelOnlyFlatPlayEnvCfg(TanchoV3WheelOnlyFlatEnvCfg):
    """Evaluation: nominal physics, no pushes, no noise, deterministic upright reset."""

    def __post_init__(self):
        super().__post_init__()
        self.scene.num_envs = 1
        self.episode_length_s = 30.0
        self.observations.policy.enable_corruption = False
        self.events.physics_material.params["static_friction_range"] = (NOMINAL_FRICTION, NOMINAL_FRICTION)
        self.events.physics_material.params["dynamic_friction_range"] = (NOMINAL_FRICTION, NOMINAL_FRICTION)
        self.events.add_base_mass = None
        self.events.reset_base.params["pose_range"] = {}
        self.events.reset_base.params["velocity_range"] = {}
        self.events.push_robot = None
